var crime = spark.read.options(Map("inferSchema"->"true", "header"->"false")).csv("/user/lw2534/stage2/crime_new.csv").toDF("id", "date", "time", "2", "3", "4", "type")
crime = crime.drop("2","3","4")
crime = crime.withColumn("date", to_date($"date", "MM/dd/yyyy"))
crime = crime.filter(crime("date").gt(lit("2018-12-31")))
crime = crime.filter(crime("date").lt(lit("2021-01-01")))
var df_before = crime.filter(crime("date").lt(lit("2020-02-29")))
var df_after = crime.filter(crime("date").gt(lit("2020-02-28")))
var df_before_hour = df_before.groupBy(hour(col("time"))).count().orderBy(hour(col("time")))
var df_after_hour = df_after.groupBy(hour(col("time"))).count().orderBy(hour(col("time")))
df_before_hour = df_before_hour.orderBy(col("count").desc)
df_after_hour = df_after_hour.orderBy(col("count").desc)
df_before_hour.show(24)
df_after_hour.show(24)