var covid = spark.read.options(Map("inferSchema"->"true", "header"->"true")).csv("/user/lw2534/stage2/epid_clean.csv")
covid = covid.filter(covid("location")==="US_NY_NYC")
covid = covid.filter(covid("date").gt(lit("2020-01-23")))
covid = covid.filter(covid("date").lt(lit("2021-01-01")))
var covid_new_c = covid.select("new_confirmed")
var covid_new_d = covid.select("new_deceased")
var covid_new_r = covid.select("new_recovered")
var covid_new_tc = covid.select("total_confirmed")
var covid_new_td = covid.select("total_deceased")
covid_new_c.coalesce(1).write.option("header","true").csv("stage2/new_confirmed.csv")
covid_new_d.coalesce(1).write.option("header","true").csv("stage2/new_deceased.csv")
covid_new_r.coalesce(1).write.option("header","true").csv("stage2/new_recovered.csv")
covid_new_tc.coalesce(1).write.option("header","true").csv("stage2/total_confirmed.csv")
covid_new_td.coalesce(1).write.option("header","true").csv("stage2/total_deceased.csv")
var covid_month_nc = covid.groupBy(month(col("date")).alias("month")).agg(sum(col("new_confirmed")).alias("sum_new_confirmed"))
var covid_month_nd = covid.groupBy(month(col("date")).alias("month")).agg(sum(col("new_deceased")).alias("sum_new_deceased"))
var covid_month_nr = covid.groupBy(month(col("date")).alias("month")).agg(sum(col("new_recovered")).alias("sum_new_recovered"))
var covid_month_tc = covid.groupBy(month(col("date")).alias("month")).agg(sum(col("total_confirmed")).alias("sum_total_confirmed"))
var covid_month_td = covid.groupBy(month(col("date")).alias("month")).agg(sum(col("total_deceased")).alias("sum_total_deceased"))
var covid_month_new_c = covid_month_nc.select("sum_new_confirmed")
var covid_month_new_d = covid_month_nd.select("sum_new_deceased")
var covid_month_new_r = covid_month_nr.select("sum_new_recovered")
var covid_month_new_tc = covid_month_tc.select("sum_total_confirmed")
var covid_month_new_td = covid_month_td.select("sum_total_deceased")
covid_new_c.coalesce(1).write.option("header","true").csv("stage2/month_new_confirmed.csv")
covid_new_d.coalesce(1).write.option("header","true").csv("stage2/month_new_deceased.csv")
covid_new_r.coalesce(1).write.option("header","true").csv("stage2/month_new_recovered.csv")
covid_new_tc.coalesce(1).write.option("header","true").csv("stage2/month_total_confirmed.csv")
covid_new_td.coalesce(1).write.option("header","true").csv("stage2/month_total_deceased.csv")